# This is a basic workflow that is manually triggered

name: Start an NBA game market maker bot

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      game_id:
        description: 'Id of the game from odds API'
        type: string
        required: true
      
      token_id:
        description: 'Id of the conditional token related'
        type: string
        required: true
      
      team:
        description: 'Team name related to the conditional token'
        type: string
        required: true
      
      sport:
        description: 'Type of sport'
        type: choice
        default: "basketball_nba"
        options:
          - "basketball_nba"
          - "basketball_nba_championship_winner"
          - "basketball_ncaab"
          - "basketball_euroleague"
        required: true
      
      region:
        description: 'Region of the match'
        type: choice
        default: "us"
        options:
          - "us"
          - "uk"
          - "eu"
          - "au"
        required: true
      
      market:
        description: 'Type of market'
        type: choice
        default: "h2h"
        options:
          - "h2h"
          - "spreads"
        required: true


jobs:
  bot_creation:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.A1_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.A1_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      KUBE_CONFIG_DATA: ${{ secrets.STAGING_KUBE_CONFIG_DATA }}
      ECR_REPOSITORY: polymarket
      IMAGE_TAG: mmk_nba_game_${{ github.event.inputs.game_id }}_${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure git
        run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push keeper image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

        run: |
          docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Create kubernetes file
        env:
          GAME_ID: ${{ github.event.inputs.game_id }}
          TOKEN_ID: ${{ github.event.inputs.token_id }}
          SPORT: ${{ github.event.inputs.sport }}
          REGION: ${{ github.event.inputs.region }}
          MARKET: ${{ github.event.inputs.market }}
          TEAM: ${{ github.event.inputs.team }}
          BANDS_FILE: "bands.json"

        run: |
          ./create_nba_game_bot_k8s_deployment.sh $BANDS_FILE $TOKEN_ID $SPORT $REGION $MARKET $GAME_ID "$TEAM" $IMAGE_TAG

      - name: Deploy market maker bot
        uses: ckuroki/kubectl-aws-eks@v1
        env:
          FILE_NAME: mmk-nba-game-${{ github.event.inputs.game_id }}.yaml
        
        with:
          args: apply -f $FILE_NAME

      - name: Bot deployed
        run: |
          echo "Game ${{ github.event.inputs.game_id }} bot deployed"
